### ISSUE TITLE
Script stuck on Apple Logo

### ISSUE THREAD

**Issue by MichaelNelsonLoganSchools** [brandonusher/Apple-ID-AppleScript#47]
When running the script, on iTunes 12.1.2, It opens iTunes and goes to the iBooks page, hits the apple logo, then opens the Sign In page. However once it gets to this step, it says 'Script Error - System Events got an error. Can't get scroll area 1 of application process "iTunes". Invalid Index.

I've run the script on OSX 10.10 and 10.11 and I get the same error both times.

I can sometimes (with really good timing) bypass this simply by pressing the 'Creat Apple ID' button.

I've tried finding a more updated version of iTunes but haven't been able to find 12.2 or 12.3. I can find 12.3.3, but it gives the same error.

**Comment by brandonusher** [comment]
Hi @MichaelNelsonLoganSchools 

Sorry to say, but this repo is no longer kept up due to lack of time as well as lack of need at my current job.

I can tell you that the issue you are seeing is why I added the clicking of the Apple Logo. It provided a way to bypass apple requiring some sort of mouse movement but it no longer works. I tried to find a way to wiggle the mouse a bit as well, but to no avail.

If you are able to find a way to fix this, I will gladly accept your pull request.

**Comment by kochalex** [comment]
Also @MichaelNelsonLoganSchools, depending on your use case, instead of running this script you may be able to use Managed Apple IDs that are coming with Apple School Manager.  Talk to your Apple rep and/or see: http://www.apple.com/education/it/

**Comment by MichaelNelsonLoganSchools** [comment]
Thanks for the quick feedback! I'll see if managed accounts will work for us.

**Comment by BillCampbell** [comment]
I have been looking at this script on and off last week with the hope of trying to fix it. It seems obvious now, but I just figured out at least one problem (hopefully THE problem) with why it no longer works even on what was previously supported version of Mac OS and iTunes.  iBooks is no longer an app you can get in the app store because it is now built-in to iOS. While you can go to the app page, the Get button is grayed out and not functional.  Maybe the answer is changing from iBooks to iTunes U as the free app to use to get to the Create Apple ID button that won't require a credit card.

**Comment by BillCampbell** [comment]
@brandonusher After a number of edits, I have the script currently working on iTunes 12.4.3 and Mac OS 10.11.6. I'm new to contributing source on GitHub, but I believe I need to be added as a contributor of some sort so I can push the local branch I created with my changes to your project. Then I can submit that as a pull request to the master branch.  Keeping it all in this project seems better than me creating my own fork as I don't think I'll be working on this much in the future However, I did make one change using a global variable to make it easier to deal with future changes in the app page layout, which is one of the things that broke the previous version in addition to iBooks no longer being an optional app.  Most of the problems seemed related to the structure of the html app page not necessarily the iTunes version.

**Comment by brandonusher** [comment]
@BillCampbell I have added you. Please go ahead and create a new branch called "issue 47" and check it out. Once you do that, please update the code to your version that is working, push it to GitHub and create a pull request.

**Comment by brandonusher** [comment]
Also @BillCampbell, Did you by chance get it to work even when requiring mouse movements as mentioned in #34 ?

**Comment by BillCampbell** [comment]
@brandonusher Do you want me to merge the pull request or do you want to check it out first and do it yourself?

**Comment by brandonusher** [comment]
@BillCampbell You can go ahead and merge it since you've done all the testing, you may as well get the credit :)

**Comment by brandonusher** [comment]
So I will go on a limb and say this issue is closed with #50 

If that is not the case, hopefully someone will speak up

**Comment by BillCampbell** [comment]
@brandonusher I wouldn't say I thoroughly tested it, but it worked for me on a limited run. That's better than it did a few days ago, which was not at all.  This has been a learning experience as I never worked with AppleScript prior to last week.  Shout out to the utilities Script Debugger and UI Browser and the limited duration free trials.  No way I would have figured any of this out in the time I had without them.
