### ISSUE TITLE
It does't work on iTunes 12.5.4

### ISSUE THREAD

**Issue by CoderZlee** [brandonusher/Apple-ID-AppleScript#55]
Why not continue to maintain this tool

**Comment by brandonusher** [comment]
My thought is that Apple is coming out with better Student Apple ID functionality where the IT Administrators have better ways of managing the Apple IDs for Students en-masse than you could with "Real" Apple ID's.

Also because of being able to now assign apps to Devices vs Apple ID's, I found this script to become unneeded by myself and many others.
